/*GENERATED BY OBNC 0.16.1*/

#ifndef Reals_h
#define Reals_h

#include <obnc/OBNC.h>

#define Reals__RealToInt_ esp32oberoncom__Reals__RealToInt_
void Reals__RealToInt_(OBNC_REAL r_, OBNC_INTEGER *i_);

#define Reals__IntToReal_ esp32oberoncom__Reals__IntToReal_
void Reals__IntToReal_(OBNC_INTEGER i_, OBNC_REAL *r_);

#define Reals__Init esp32oberoncom__Reals__Init
void Reals__Init(void);

#endif
