/*GENERATED BY OBNC 0.16.1*/

#ifndef Out_h
#define Out_h

#include <obnc/OBNC.h>

#define Out__Baud115K_ 694

#define Out__Baud76800_ 1041

#define Out__Baud38400_ 2083

#define Out__Baud19200_ 4166

#define Out__Baud9600_ 8333

#define Out__Open_ compilertestsu__Out__Open_
void Out__Open_(void);

#define Out__Flush_ compilertestsu__Out__Flush_
void Out__Flush_(void);

#define Out__Char_ compilertestsu__Out__Char_
void Out__Char_(char ch_);

#define Out__String_ compilertestsu__Out__String_
void Out__String_(const char s_[], OBNC_INTEGER s_len);

#define Out__Int_ compilertestsu__Out__Int_
void Out__Int_(OBNC_INTEGER x_, OBNC_INTEGER n_);

#define Out__Hex_ compilertestsu__Out__Hex_
void Out__Hex_(OBNC_INTEGER x_, OBNC_INTEGER n_);

#define Out__Real_ compilertestsu__Out__Real_
void Out__Real_(OBNC_REAL x_, OBNC_INTEGER n_, OBNC_INTEGER k_);

#define Out__Ln_ compilertestsu__Out__Ln_
void Out__Ln_(void);

#define Out__SetBaudRate_ compilertestsu__Out__SetBaudRate_
void Out__SetBaudRate_(OBNC_INTEGER baudRate_);

#define Out__Setup_ compilertestsu__Out__Setup_
void Out__Setup_(void);

#define Out__Init compilertestsu__Out__Init
void Out__Init(void);

#endif
