/*GENERATED BY OBNC 0.16.1*/

#include "Out.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "Out.Mod"

void Out__Open_(void)
{
}


static OBNC_INTEGER FifoCount_(void)
{
	OBNC_INTEGER c_, r_;

	OBNC_GET(1072955420, r_, OBNC_INTEGER);
	c_ = OBNC_MOD(OBNC_ASR(r_, 16), 256);
	return c_;
}


void Out__Flush_(void)
{

	while (FifoCount_() > 0) {
	}
}


void Out__Char_(char ch_)
{

	while (FifoCount_() > 120) {
	}
	OBNC_PUT(1072955392, OBNC_ORD((unsigned char) (ch_)), OBNC_INTEGER);
}


void Out__String_(const char s_[], OBNC_INTEGER s_len)
{
	OBNC_INTEGER i_;

	i_ = 0;
	while ((i_ < s_len) && (s_[OBNC_IT(i_, s_len, 48)] != '\x00')) {
		Out__Char_(s_[OBNC_IT(i_, s_len, 49)]);
		OBNC_INC(i_);
	}
}


void Out__Int_(OBNC_INTEGER x_, OBNC_INTEGER n_)
{
	OBNC_INTEGER i_, x0_;
	char a_[10];

	i_ = 0;
	if (x_ < 0) {
		x0_ = -x_;
		OBNC_DEC(n_);
	}
	else {
		x0_ = x_;
	}
	do {
		a_[OBNC_IT(i_, 10, 66)] = OBNC_CHR((OBNC_MOD(x0_, 10)) + 48);
		x0_ = OBNC_DIV(x0_, 10);
		OBNC_INC(i_);
	} while (! (x0_ == 0));
	while (n_ > i_) {
		Out__Char_(' ');
		OBNC_DEC(n_);
	}
	if (x_ < 0) {
		Out__Char_('-');
	}
	do {
		OBNC_DEC(i_);
		Out__Char_(a_[OBNC_IT(i_, 10, 76)]);
	} while (! (i_ == 0));
}


void Out__Hex_(OBNC_INTEGER x_, OBNC_INTEGER n_)
{
	OBNC_INTEGER i_, y_;
	char a_[10];

	i_ = 0;
	do {
		y_ = OBNC_MOD(x_, 16);
		if (y_ < 10) {
			a_[OBNC_IT(i_, 10, 88)] = OBNC_CHR(y_ + 48);
		}
		else {
			a_[OBNC_IT(i_, 10, 90)] = OBNC_CHR(y_ + 55);
		}
		x_ = OBNC_DIV(x_, 16);
		OBNC_INC(i_);
	} while (! (i_ == 8));
	while (n_ > 8) {
		Out__Char_(' ');
		OBNC_DEC(n_);
	}
	do {
		OBNC_DEC(i_);
		Out__Char_(a_[OBNC_IT(i_, 10, 98)]);
	} while (! (i_ == 0));
}


static OBNC_REAL Ten_(OBNC_INTEGER n_)
{
	OBNC_REAL t_, p_;

	t_ = 1.0;
	p_ = 10.0;
	while (n_ > 0) {
		if (OBNC_ODD(n_)) {
			t_ = p_ * t_;
		}
		p_ = p_ * p_;
		n_ = OBNC_DIV(n_, 2);
	}
	return t_;
}


void Out__Real_(OBNC_REAL x_, OBNC_INTEGER n_, OBNC_INTEGER k_)
{
	OBNC_INTEGER i_, m_;
	int neg_;
	char d_[12];

	if (x_ == 0.0) {
		Out__String_("  0", 4);
	}
	else {
		if (x_ < 0.0) {
			x_ = -x_;
			neg_ = 1;
		}
		else {
			neg_ = 0;
		}
		if (k_ > 7) {
			k_ = 7;
		}
		x_ = Ten_(k_) * x_;
		m_ = OBNC_FLOOR(x_ + 0.5);
		i_ = 0;
		do {
			d_[OBNC_IT(i_, 12, 130)] = OBNC_CHR((OBNC_MOD(m_, 10)) + 48);
			m_ = OBNC_DIV(m_, 10);
			OBNC_INC(i_);
		} while (! (m_ == 0));
		Out__Char_(' ');
		while (n_ > (i_ + 3)) {
			Out__Char_(' ');
			OBNC_DEC(n_);
		}
		if (neg_) {
			Out__Char_('-');
			OBNC_DEC(n_);
		}
		else {
			Out__Char_(' ');
		}
		while (i_ > k_) {
			OBNC_DEC(i_);
			Out__Char_(d_[OBNC_IT(i_, 12, 136)]);
		}
		Out__Char_('.');
		while (k_ > i_) {
			OBNC_DEC(k_);
			Out__Char_('0');
		}
		while (i_ > 0) {
			OBNC_DEC(i_);
			Out__Char_(d_[OBNC_IT(i_, 12, 139)]);
		}
	}
}


void Out__Ln_(void)
{

	Out__Char_('\x0d');
	Out__Char_('\x0a');
}


void Out__SetBaudRate_(OBNC_INTEGER baudRate_)
{

	OBNC_PUT(1072955412, baudRate_, OBNC_INTEGER);
}


void Out__Setup_(void)
{

	Out__SetBaudRate_(694);
}


void Out__Init(void)
{
	static int initialized = 0;

	if (! initialized) {
		OBNC_C_ASSERT(sizeof (OBNC_INTEGER) == sizeof (void *)); /*SYSTEM procedure requirement*/
		Out__Setup_();
		initialized = 1;
	}
}
