/*GENERATED BY OBNC 0.16.1*/

#include "Out.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "TestFunction0.Mod"

static OBNC_INTEGER x_;

static OBNC_INTEGER P1_(OBNC_INTEGER i_);

static OBNC_INTEGER P1_P2_Local(OBNC_INTEGER j_, OBNC_INTEGER z_)
{
	OBNC_INTEGER k_;

	k_ = z_;
	return k_ + j_;
}


static OBNC_INTEGER P1_(OBNC_INTEGER i_)
{
	return i_ + P1_P2_Local(i_, 2);
}


#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	Out__Init();
	x_ = P1_(1);
	Out__Int_(x_, 0);
	return 0;
}
