/*GENERATED BY OBNC 0.16.1*/

#include ".obnc/SYS.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "SYS.Mod"

extern void exit(int);

union {
  OBNC_REAL f;
  OBNC_INTEGER i;
} w;

void SYS__IntToReal_(OBNC_INTEGER i_, OBNC_REAL *r_)
{
  w.i = i_; *r_ = w.f;
}


void SYS__RealToInt_(OBNC_REAL r_, OBNC_INTEGER *i_)
{
  w.f = r_;  *i_ = w.i;
}


void SYS__Exit_(OBNC_INTEGER i_)
{
  exit(i_);
}


void SYS__Init(void)
{
}
