/*GENERATED BY OBNC 0.16.1*/

#ifndef SYS_h
#define SYS_h

#include <obnc/OBNC.h>

#define SYS__IntToReal_ src__SYS__IntToReal_
void SYS__IntToReal_(OBNC_INTEGER i_, OBNC_REAL *r_);

#define SYS__RealToInt_ src__SYS__RealToInt_
void SYS__RealToInt_(OBNC_REAL r_, OBNC_INTEGER *i_);

#define SYS__Exit_ src__SYS__Exit_
void SYS__Exit_(OBNC_INTEGER i_);

#define SYS__Init src__SYS__Init
void SYS__Init(void);

#endif
