/*GENERATED BY OBNC 0.16.1*/

#include ".obnc/SYS.h"
#include <obnc/OBNC.h>

#include <stdio.h>
#include <stdlib.h> 
#include <unistd.h> 

#define OBERON_SOURCE_FILENAME "SYS.Mod"

extern void exit(int);

union {
  OBNC_REAL f;
  OBNC_INTEGER i;
} w;

void SYS__IntToReal_(OBNC_INTEGER i_, OBNC_REAL *r_)
{
  w.i = i_; *r_ = w.f;
}


void SYS__RealToInt_(OBNC_REAL r_, OBNC_INTEGER *i_)
{
  w.f = r_;  *i_ = w.i;
}


void SYS__Exit_(OBNC_INTEGER i_)
{
  exit(i_);
}

static char cmd[1024];

OBNC_INTEGER SYS__Assembler_(const char fromFile_[], OBNC_INTEGER fromFile_len, const char toFile_[], OBNC_INTEGER toFile_len)
{
  #if 0
    // This doesn't work... yet.
    const char *pgm = "xtensa-esp32-elf-gcc";
    char * args[] = {
      "-x assembler-with-cpp",
      "-c",
      "-O0",
      "-Wall",
      "-fmessage-length=0",
        "-mlongcalls",
      "-mauto-litpools",
      "-mtext-section-literals",
      "-fstrict-volatile-bitfields",
      "-g",
      (char *) fromFile_,
      "-o",
      (char *) toFile_,
      NULL
    };
    
    execv(pgm, args);
    perror("Call to assembler error");
    return 1;
  #else
    int res;

    strcpy(cmd, "xtensa-esp32-elf-gcc -x assembler-with-cpp -c -O0 -Wall -fmessage-length=0 -mlongcalls -mauto-litpools -mtext-section-literals -fstrict-volatile-bitfields -g ");
    strcat(cmd, fromFile_);
    strcat(cmd, " -o ");
    strcat(cmd, toFile_);

    if ((res = system(cmd))) perror("Last assembler msg");
    return res;
  #endif
}


void SYS__Init(void)
{
}
